# Codecov.io configuration
codecov:
  branch: develop  # override the default branch

coverage:
  precision: 2  # 2 = xx.xx%, 0 = xx%
  round: down # default down|up|nearest
  range: 70...90 # default 70...90. red...green

  ignore: # files and folders for processing
    - external/catch.hpp
