#########################
# project configuration #
#########################

# C++ project
language: cpp

dist: trusty
sudo: required

git:
  submodules: false

###################
# global settings #
###################

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "yhvqVR4Pycv8M/kLjX6KAuD8cmBdklf7PMyEFTsELo5qbC+ZDduSn2b6fGB58W1OoQFaeOj0VLgy8RKw4cClc7Nu64d201UarD52qR6O/i+Bzbtv0tuV1CToW+SufUCDTZEeqNmFWOvtO7vt1oH+So7WooT1jQ8rFtyFH73BYrwMzA17M8Ksg2PGqJP0YunfiSEV0Nyol6azEavGlZ9O9t5SFw/l+K15iWt4PGV3wQ2ZwSuILS6ncWZ6KYishywTdE21jtI7YVTL3XwYP/qWpSo8j8E+mivuS1Za1kI8geyvtNkQn3HIqbgW4cAMz9fCwVMYqAAgf2it/G7iFuGs2QZN5q70IPdFNDK95+pKWFOQqhTNoPE9LAaAb2kW6XY6I0dDf6x0vyXzerJaCey44fuxTo5kmTS+e0dTA5SS8TmPkoTjpIsGkfCyleytL3GOnWkdt1g22Fzr36WL7X1KFPCF2+m9lXXOtEeZZvyGvj7LIyLWlEyzblDuJ5WgpW7mknU0va5tTmtIaVFJFkmyhuk0c1/jtgAXn42Ob913y2MRy9bokWyzOq/BvcevC5SU0GElzkdW07qrV3l7Bg5iS+0P6K38RO/7hCJ/zQUIMEhAEzT5fQ6EbdB6OR8cPIxo6ESFHvttx0zxRYV0KDG57pA/6YxOula/pAUlitB4bQw="


##################
# Before install #
##################
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  
################
# build matrix #
################
matrix:
  include:
    # GCC 4.9
    - compiler: gcc-4.9
      env: COMPILER=g++-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9    
      before_script: export CXX=g++-4.9

    # GCC 5
    - compiler: gcc-5
      env: COMPILER=g++-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      before_script: export CXX=g++-5

    # Clang 3.9 and static analysis
    - os: linux
      compiler: clang-3.9
      addons:
       apt:
         sources:
           - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
           - sourceline: 'deb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
         packages:
           - clang-3.9
      env: 
        - COMPILER=clang++-3.9
        - CONFIG=scan-build
        - ASAN="ON"
        - MSAN="ON"
        - TSAN="ON"
        - UBSAN="ON"
        - STATIC_ANALYZER="ON"
        - CLANG_FORMAT="ON"
        - CLANG_TIDY="ON"
      before_install:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update -qq
        - sudo apt-get install -qq clang-3.9
      after_success:
        - scan-build-3.9 cmake ..
        - scan-build-3.9 make

    # Coverity scan 
    - os: linux
      compiler: gcc-5
      env:
        - COMPILER=g++-5
        - SPECIAL=coverity
      before_install: 
        - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt
      before_script: export CXX=g++-5
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'libeigen3-dev']
        coverity_scan:
          project:
            name: "cb-geo/lem-gmsh"
            description: "LEM GMSH Coverity scan build submitted via Travis CI"
          notification_email: cued.geomechanics@gmail.com
          build_command_prepend: "sudo ln -sf /usr/bin/g++-5 /usr/bin/g++ && export CXX=g++ && g++ --version && cmake . && make clean"
          build_command: "make"
          branch_pattern: coverity_scan
    
    # Codecov
    - compiler: gcc-5
      env:
        - COMPILER=g++-5
        - SPECIAL=codecoverage
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'ruby']
      before_script:
        - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
        - tar xf lcov_1.11.orig.tar.gz
        - sudo make -C lcov-1.11/ install
        - export CXX=g++-5
      after_success:
        - rm -rf ./* && cmake -DENABLE_COVERAGE=On ..
        - make clean && make
        # - ./lem-gmsh
        - make gcov
        - make lcov
        - bash <(curl -s https://codecov.io/bash) -X gcov

    # Valgrind and cppcheck
    - compiler: gcc-5
      env:
        - COMPILER=g++-5
        - SPECIAL=valgrind
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'cppcheck', 'valgrind']
      before_script: export CXX=g++-5
      after_success:
        # - valgrind --error-exitcode=1 --leak-check=full ./lem-gmsh
        - cd .. && cppcheck --enable=warning --inconclusive --force --std=c++11 src/*.cc include/*.h include/*.tcc --error-exitcode=1

################
# build script #
################

script:
    - mkdir build
    - cd build
    - cmake ..
    - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make ; fi

notifications:
  slack:
    rooms:
      - cb-geo:0N3fJy823MGsJvcDB91m4p8H#lem
