#########################
# project configuration #
#########################

# C++ project
language: cpp

dist: trusty
sudo: required

git:
  submodules: false

###################
# global settings #
###################

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "vAsvNe+g89Djw1x4xd4V1xUV4xV7jYzxbA74U3sTf5GKaSVALUzLPvMCIgzGceek59c7ba3D8TK54qAFw2yjfcmWQMrPex/dJmYzh9XZqmh01+yAGJmNar/omC7nb3FeA621WGfDhIN23Ts/VdDTjthZbnIgpnIZsucfhPQ8iG7fHfaXnq2id4oCitsaEpjXhe6UWFrx+mLjJvjkhk3c7ASCg12ybSE0uDDMYHODzPe3iMP76uIRdJxXnHFdofS9xrW1YRUoMDzJOz5XlbUJLjA13hSzSX5NJcT5WorKltHBUMfBo7OWKsjCdt9o6xoXWbhEa3+18K1ncyKiiQ0fGSf0vsCUq/FEZUhxGOM9sbY/qywxB2hkk3MYmd4YQn6ZcsQ08NBYdR0z/QY51j1u6maz6tX88a50Ugq7q8Hu3g6pYlygySWh1VTQNdLI0bm7Tjqo9YEWwpkaolGWYR9ctp+xHV+bGqlh7MXNHeeor8PO7waW6ey2VJCYg2fcmU+ucYYwTUi8A/0W3jYuXJ3HztdO43uk9BDC6JIZ4NshRIfgXYLXB0MmJfq/epIda/TP/m2QeGoFGAFYFmaFsQ24ulqXUrzfsmqwgBjE/3v2ZGsjeMQX8iPV/K4o1LDpKCSbM+R2au0cXNn6ZYldHah2HpZubn0QsA8kg+AW6ieqWME="


##################
# Before install #
##################
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get install -qq libeigen3-dev
  - sudo apt-get update -qq
  
################
# build matrix #
################
matrix:
  include:
    # Coverity scan 
    - os: linux
      compiler: gcc-5
      env:
        - COMPILER=g++-5
        - SPECIAL=coverity
      before_install: 
        - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt
      before_script: export CXX=g++-5
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'libeigen3-dev']
        coverity_scan:
          project:
            name: "cb-geo/lem-gmsh"
            description: "LEM GMSH Coverity scan build submitted via Travis CI"
          notification_email: cued.geomechanics@gmail.com
          build_command_prepend: "sudo ln -sf /usr/bin/g++-5 /usr/bin/g++ && export CXX=g++ && g++ --version && cmake . && make clean"
          build_command: "make"
          branch_pattern: coverity_scan    

################
# build script #
################

script:
    - mkdir build
    - cd build
    - cmake ..
    - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make ; fi

notifications:
  slack:
    rooms:
      - cb-geo:0N3fJy823MGsJvcDB91m4p8H#lem
