#########################
# project configuration #
#########################

# C++ project
language: cpp

dist: trusty
sudo: required

git:
  submodules: false

###################
# global settings #
###################

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "W6FP6GEDzbmWDiKAZ+klATdSaV4ul5RhZpzTVfBUmXHUeWKBCtVksxsLmvYt85Isg3kXyajzKbfSMqA7ZTd49FQIs+T3obIM2YUyhpfebp8gAW5M4bcvWUEgJk1lNRUFIQTEN5LWRixSXTxSzvi8Ok3EaI54yfGJ6qTvOEGWjBK3ZzYzXi8r2eTKtyz/DSa/qQFDBQEKiCwBjYqViWwRgE2+1wdc3Qujc5xEV0q7DfxIexQeCTKm17sEGPGoFSaPG7AeIc7c6KidEZMOVEGwmlqZfPr8Q2gRhIaA6VT/yJa5P4iochZ1lARunyYsLWhlGRaw+XRdDbcEFW9J5HcYWdZADDk3pnXYwClKH9ZNyO/HWx/GC8asH49jrEVHijvmwUmYwAvfEiZhNnJZJCoN9igvdLd/9vcfCCaNg1gY7x1K2t6dS0/Lsq7bP3hENt5PzocCziNAvD5sdhxwc9zZm2jBDTBQc+CGN+yMPzRsRVg/gwB/QIDbJmOBRx+7mFWjKnzg6wjB0ZkyvhGIoT40RACgW6XHNF5GQFyM1xDGFSFh4f86BWisghq2Pqk6TSrbswh3b/TcCV+d+9unIgT7DWaqds22hs6cqnM6kjUE4cN4UlkOmKbmVVq72Ix5I/BNzwTLL1Cok2B7Pgpza5MNKw87vP6KYG9hvyg5zbTnpVA="

##################
# Before install #
##################
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  
################
# build matrix #
################
matrix:
  include:
    # GCC 4.9
    - compiler: gcc-4.9
      env: COMPILER=g++-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9    
      before_script: export CXX=g++-4.9

    # GCC 5
    - compiler: gcc-5
      env: COMPILER=g++-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      before_script: export CXX=g++-5

    # Clang 3.9 and static analysis
    - os: linux
      compiler: clang-3.9
      addons:
       apt:
         sources:
           - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
           - sourceline: 'deb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
         packages:
           - clang-3.9
      env: 
        - COMPILER=clang++-3.9
        - CONFIG=scan-build
        - ASAN="ON"
        - MSAN="ON"
        - TSAN="ON"
        - UBSAN="ON"
        - STATIC_ANALYZER="ON"
        - CLANG_FORMAT="ON"
        - CLANG_TIDY="ON"
      before_install:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update -qq
        - sudo apt-get install -qq clang-3.9
      after_success:
        - scan-build-3.9 cmake ..
        - scan-build-3.9 make

    # Coverity scan 
    - os: linux
      compiler: gcc-5
      env:
        - COMPILER=g++-5
        - SPECIAL=coverity
      before_install: 
        - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt
      before_script: export CXX=g++-5
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'libeigen3-dev']
        coverity_scan:
          project:
            name: "cb-geo/lem-gmsh"
            description: "LEM GMSH Coverity scan build submitted via Travis CI"
          notification_email: cued.geomechanics@gmail.com
          build_command_prepend: "sudo ln -sf /usr/bin/g++-5 /usr/bin/g++ && export CXX=g++ && g++ --version && cmake . && make clean"
          build_command: "make"
          branch_pattern: coverity_scan
    
    # Codecov
    - compiler: gcc-5
      env:
        - COMPILER=g++-5
        - SPECIAL=codecoverage
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'ruby']
      before_script:
        - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
        - tar xf lcov_1.11.orig.tar.gz
        - sudo make -C lcov-1.11/ install
        - export CXX=g++-5
      after_success:
        - rm -rf ./* && cmake -DENABLE_COVERAGE=On ..
        - make clean && make
        # - ./lem-gmsh
        - make gcov
        - make lcov
        - bash <(curl -s https://codecov.io/bash) -X gcov

    # Valgrind and cppcheck
    - compiler: gcc-5
      env:
        - COMPILER=g++-5
        - SPECIAL=valgrind
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'cppcheck', 'valgrind']
      before_script: export CXX=g++-5
      after_success:
        # - valgrind --error-exitcode=1 --leak-check=full ./lem-gmsh
        - cd .. && cppcheck --enable=warning --inconclusive --force --std=c++11 src/*.cc include/*.h include/*.tcc --error-exitcode=1

    # OSX / Clang
    - os: osx
      osx_image: xcode7.3

    - os: osx
      osx_image: xcode8

################
# build script #
################

script:
    - mkdir build
    - cd build
    - cmake ..
    - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make ; fi

notifications:
  slack:
    rooms:
      - cb-geo:0N3fJy823MGsJvcDB91m4p8H#lem
